### ISSUE TITLE
Allow ArgoCD Application to deploy in external namespace

### ISSUE THREAD

**Issue by Javatar81** [Javatar81/devjoy#33]
https://argocd-operator.readthedocs.io/en/latest/usage/deploy-to-different-namespaces/

**Comment by Javatar81** [comment]
We need to set this when a project is created in a namespace != devEnv.metadata.namespace:


```
apiVersion: v1
kind: Namespace
metadata:
  name: bar
  labels:
    argocd.argoproj.io/managed-by: foo // namespace of managing Argo CD instance
```
