### ISSUE TITLE
Adjust readiness and liveness probes

### ISSUE THREAD

**Issue by Javatar81** [Javatar81/devjoy#77]
Use readiness and liveness as proposed here: https://github.com/rhpds/gitea-operator/

Let's try this for readiness:

```
 failureThreshold: 3
 initialDelaySeconds: 5
 periodSeconds: 10
 successThreshold: 1
 timeoutSeconds: 1
```

 and for liveness:

```
failureThreshold: 3
initialDelaySeconds: 120
periodSeconds: 10
successThreshold: 1
timeoutSeconds: 10
```

**Comment by Javatar81** [comment]
See https://github.com/rhpds/gitea-operator/blob/main/roles/gitea-ocp/templates/deployment.yaml.j2

**Comment by Javatar81** [comment]
```
readinessProbe:
  httpGet:
    path: /
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 15
  timeoutSeconds: 1
  periodSeconds: 20
  successThreshold: 1
  failureThreshold: 3
livenessProbe:
  httpGet:
    path: /
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 15
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
```
