### ISSUE TITLE
Readiness probe fails for deployed application because Quarkus returns 403 for path /

### ISSUE THREAD

**Issue by Javatar81** [Javatar81/devjoy#79]
The default starter for Helm does not allow to customize liveness and readiness probe and Quarkus expects another path, e.g. /q/health/ready and /q/health/live

```yaml
containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
```
